config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/login' => 'sessions#login', :as => :login
 post 'sessions/login_attempt' => 'sessions#login_attempt'

  get 'sessions/home'

  get 'sessions/profile'

  get 'sessions/setting'
  
  
  resources :events

  resources :dogs

  resources :handlers
  
  resources :entries
  
  get 'signup' => 'handlers#signup', :as => :signup
  post 'do_signup' => 'handlers#do_signup', :as => :do_signup
  
  
  root 'main#index'
  
  get "login" => "sessions#login"
  get "logout" => "sessions#logout"
  get "home" => "sessions#home"
  get "profile" => "sessions#profile"
  get "setting" => "sessions#setting"
  
  
  

end

app/models/handler.rb
class Handler < ActiveRecord::Base
  
  has_many :dogs
  
  

  
  attr_accessor :password
  
  
  validates :email, :presence => true, :uniqueness => true
  validates_presence_of :first_name, :last_name
  validates :password, :confirmation => true
  #validates_confirmation_of :password
  #Only on Create so other actions like update password attribute can be nil
  #validates_length_of :password, :in => 6..20, :on => :create
  validates_uniqueness_of :reg, :message => "An account with that registration number already exists"
  
  #not sure why this doesn't work?
  # :email, :first_name, :last_name, :reg, :password, :password_confirmation

  before_save :encrypt_password
  after_save :clear_password
  
  def encrypt_password
    unless password.blank?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end
  
  
def self.authenticate(email = "", password = "")
  
  handler = Handler.find_by_email(email)
  if handler && handler.encrypted_password == BCrypt::Engine.hash_secret(password, handler.salt)
    return handler
  else
    return false
  end
end   


  
  
end

app/controllers/handlers_controller.rb
class HandlersController < ApplicationController
  before_action :set_handler, only: [:show, :edit, :update, :destroy]
  before_filter :save_login_state, :only => [:new, :create, :signup, :do_signup]

  # GET /handlers
  # GET /handlers.json
  def index
    @handlers = Handler.all
  end

  # GET /handlers/1
  # GET /handlers/1.json
  def show
  end

  # GET /handlers/new
  def new
    @handler = Handler.new
  end

  # GET /handlers/1/edit
  def edit
  end

  # POST /handlers
  # POST /handlers.json
  def create
    @handler = Handler.new(handler_params)

    respond_to do |format|
      if @handler.save
        format.html { redirect_to @handler, notice: 'Handler was successfully created.' }
        format.json { render :show, status: :created, location: @handler }
      else
        format.html { render :new }
        format.json { render json: @handler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /handlers/1
  # PATCH/PUT /handlers/1.json
  def update
    respond_to do |format|
      if @handler.update(handler_params)
        format.html { redirect_to @handler, notice: 'Handler was successfully updated.' }
        format.json { render :show, status: :ok, location: @handler }
      else
        format.html { render :edit }
        format.json { render json: @handler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /handlers/1
  # DELETE /handlers/1.json
  def destroy
    @handler.destroy
    respond_to do |format|
      format.html { redirect_to handlers_url, notice: 'Handler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  
  
  def signup
    @handler = Handler.new
  end
  
  
  def do_signup
    
    @handler = Handler.new(handler_params)
      if @handler.save
        flash[:notice] = "You Signed up successfully"
        flash[:color]= "valid"
        
      else
        flash[:notice] = "Form is invalid"
        flash[:color]= "invalid"
        render "signup"
      end
      
    
  end
  
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_handler
      @handler = Handler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def handler_params
      params.require(:handler).permit(:first_name, :last_name, :reg, :email, :password, :password_confirmation, :salt)
    end
end

app/helpers/handlers_helper.rb
module HandlersHelper
end

app/views/handlers/_form.html.erb
<%= form_for(@handler) do |f| %>
  <% if @handler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@handler.errors.count, "error") %> prohibited this handler from being saved:</h2>

      <ul>
      <% @handler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="fieldSet">
	<fieldset>
	<legend>Handler Details</legend>
		<p><%= label_tag(:email, "E-mail:", class:"field", :required => true) %>
		<%= f.text_field :email %></p>
		<p><%= label_tag :first_name, "First Name:", class:"field" %>
		<%= f.text_field :first_name %></p>
		<p><%= label_tag :last_name, "Last Name:", class:"field" %>
		<%= f.text_field :last_name %></p>
		<p><%= label_tag :reg, "Dogswest Registration:", class:"field" %>
		<%= f.text_field :reg %></p>
		<p><%= f.submit %></p>
	</fieldset>
</div>
	
	
	
	<% end %>

app/views/handlers/do_signup.html.erb
Cheers <%= @handler["first_name"] %>

app/views/handlers/edit.html.erb
<h1>Editing handler</h1>

<%= render 'form' %>

<%= link_to 'Show', @handler %> |
<%= link_to 'Back', handlers_path %>

app/views/handlers/index.html.erb
<h1>Listing handlers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Reg</th>
      <th>Email</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @handlers.each do |handler| %>
      <tr>
        <td><%= handler.first_name %></td>
        <td><%= handler.last_name %></td>
        <td><%= handler.reg %></td>
        <td><%= handler.email %></td>
           <td><%= handler.salt %></td>
        <td><%= link_to 'Show', handler %></td>
        <td><%= link_to 'Edit', edit_handler_path(handler) %></td>
        <td><%= link_to 'Destroy', handler, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Handler', new_handler_path %>

app/views/handlers/new.html.erb
<h1>New handler</h1>

<%= render 'form' %>

<%= link_to 'Back', handlers_path %>

app/views/handlers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @handler.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @handler.last_name %>
</p>

<p>
  <strong>Reg:</strong>
  <%= @handler.reg %>
</p>

<p>
  <strong>Email:</strong>
  <%= @handler.email %>
</p>

<p>
  <strong>Password: </strong>
  <%= @handler.encrypted_password %>
</p>

<%= link_to 'Edit', edit_handler_path(@handler) %> |
<%= link_to 'Back', handlers_path %>

app/views/handlers/signup.html.erb
<% @page_title = "UserAuth | Signup" -%>
<div class= "Sign_Form">
	
	
	
  <h1>Sign Up</h1>
  
  
  <div class="FieldSet">
  	<fieldset>
  
  <%= form_for(:handler, :url => {:controller => 'handlers', :action => 'do_signup'}) do |f| %>

    <p><%= label_tag :email, "Email:" %>
      <%= f.text_field :email %></p>

	<p><%= label_tag :first_name, "First Name:" %>
		<%= f.text_field :first_name %></p>
	
	<p><%= label_tag :last_name, "Last Name:" %>
		<%= f.text_field :last_name %></p>
	
	<p><%= label_tag :reg, "Dogswest Registration:" %>
		<%= f.text_field :reg %></p>


    <p><%= label_tag :password, "Password:" %> 
    	<%= f.password_field :password %></p>

    <p><%= label_tag :password_confirmation, "Password Confirmation:" %> 
    	<%= f.password_field :password_confirmation %></p>

    <%= f.submit :Signup %>
  <% end %>
  
  </fieldset></div>

  <% if @handler.errors.any? %>
	<ul class="Signup_Errors">
		<% for message_error in @handler.errors.full_messages %>
			<li>* <%= message_error %></li>
	  	<% end %>
	</ul>
  <% end %>
</div>