config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/login' => 'sessions#login', :as => :login
 post 'sessions/login_attempt' => 'sessions#login_attempt'

  get 'sessions/home'

  get 'sessions/profile'

  get 'sessions/setting'
  
  
  resources :events

  resources :dogs

  resources :handlers
  
  resources :entries
  
  get 'signup' => 'handlers#signup', :as => :signup
  post 'do_signup' => 'handlers#do_signup', :as => :do_signup
  
  
  root 'main#index'
  
  get "login" => "sessions#login"
  get "logout" => "sessions#logout"
  get "home" => "sessions#home"
  get "profile" => "sessions#profile"
  get "setting" => "sessions#setting"
  
  
  

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  
  belongs_to :handler
  
  validate :check_titles
  validates_presence_of :name, :reg, :height
  validates_numericality_of :height, :message => " must be numeric"
  validates_uniqueness_of :reg, :message => "Dog already exists"
  
  
  
  
  def check_titles
    
    #Ensure titles field is alphanumeric
    #NEED PROVISION FOR SPACE
    if ((titles =~ /\A\p{Alnum}+\z/).nil? && titles != "")
      errors.add(:titles, " are invalid. Please ensure you have entered them correctly (e.g. AD ADX)")  
    end
     
    
  end
  
  
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :reg, :titles, :breed, :height)
    end
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="fieldSet">
	<fieldset>
  		<legend>Dog Details</legend>
		<p><%= label_tag :name, "Name:", class:"field" %>
		<%= f.text_field :name %></p>
		<p><%= label_tag :titles, "Titles:", class:"field" %>
		<%= f.text_field :titles %></p>
		<p><%= label_tag :reg, "Registration Number:", class:"field" %>
		<%= f.text_field :reg %></p>
		<p><%= label_tag :height, "Height", class:"field" %>
		<%= f.select :height, [200, 300, 400, 500, 600], include_blank: "---",
			selected: f.object.height ? f.object.height : "" %></p>
		<p><%= f.submit %></p>
	</fieldset>
</div>
	
  
  
  
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<h1>Listing dogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Reg</th>
      <th>Titles</th>
      <th>Breed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= dog.reg %></td>
        <td><%= dog.titles %></td>
        <td><%= dog.breed %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>New dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Reg:</strong>
  <%= @dog.reg %>
</p>

<p>
  <strong>Titles:</strong>
  <%= @dog.titles %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @dog.breed %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>