config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/login' => 'sessions#login', :as => :login
 post 'sessions/login_attempt' => 'sessions#login_attempt'

  get 'sessions/home'

  get 'sessions/profile'

  get 'sessions/setting'
  
  
  resources :events

  resources :dogs

  resources :handlers
  
  resources :entries
  
  get 'signup' => 'handlers#signup', :as => :signup
  post 'do_signup' => 'handlers#do_signup', :as => :do_signup
  
  
  root 'main#index'
  
  get "login" => "sessions#login"
  get "logout" => "sessions#logout"
  get "home" => "sessions#home"
  get "profile" => "sessions#profile"
  get "setting" => "sessions#setting"
  
  
  

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:hosting_club, :isAgility, :isJumping, :isADO, :isJDO, :isSnooker, :isGamblers, :isStratPairs, :trial_datetime, :notes)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hosting_club %><br>
    <%= f.text_field :hosting_club %>
  </div>
  <div class="field">
    <%= f.label :isAgility %><br>
    <%= f.check_box :isAgility %>
  </div>
  <div class="field">
    <%= f.label :isJumping %><br>
    <%= f.check_box :isJumping %>
  </div>
  <div class="field">
    <%= f.label :isADO %><br>
    <%= f.check_box :isADO %>
  </div>
  <div class="field">
    <%= f.label :isJDO %><br>
    <%= f.check_box :isJDO %>
  </div>
  <div class="field">
    <%= f.label :isSnooker %><br>
    <%= f.check_box :isSnooker %>
  </div>
  <div class="field">
    <%= f.label :isGamblers %><br>
    <%= f.check_box :isGamblers %>
  </div>
  <div class="field">
    <%= f.label :isStratPairs %><br>
    <%= f.check_box :isStratPairs %>
  </div>
  <div class="field">
    <%= f.label :trial_datetime %><br>
    <%= f.datetime_select :trial_datetime %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/do_entry.html.erb
Please confirm your entries:
<br><br>
<% @events.each do |e| %>
<%= e %><br>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/enter.html.erb
Entering event

<br>
Hosting Club: <%= @event.hosting_club %><BR>
<%= @event.notes %><BR>


<%= form_tag do_entry_path do %>

	<HR>
	<TABLE BORDER=0>
	
	<TR><TD COLSPAN=2 class="form_heading">Handler Details</TD></TR>
	<TR><TD class="form_label_cell">E-mail:</TD> <TD><%= text_field_tag(:handler_email) %></TD></TR>
	<TR><TD class="form_label_cell">First name:</TD><TD><%= text_field_tag(:handler_first_name) %></TD></TR>
	<TR><TD class="form_label_cell">Last name:</TD><TD><%= text_field_tag(:handler_last_name) %></TD></TR>
	<TR><TD>&nbsp;</TD></TR>
	<TR><TD COLSPAN=2 class="form_heading">Dog Details</TD></TR>
	<TR><TD class="form_label_cell">Dog name:</TD><TD><%= text_field_tag(:dog_name) %></TD></TR>
	<TR><TD class="form_label_cell">Titles:</TD><TD><%= text_field_tag(:dog_titles) %></TD></TR>
	<TR><TD class="form_label_cell">Registration Number:</TD><TD><%= text_field_tag(:dog_registration_number) %></TD></TR>
	<TR><TD class="form_label_cell">Breed:</TD><TD><%= text_field_tag(:dog_breed) %></TD></TR>
	<TR><TD class="form_label_cell">Height:</TD><TD><%= select_tag(:dog_height, options_for_select([['-', ''], ['200', '200'], ['300', '300'], ['400', '400'], ['500', '500'], ['600', '600']])) %></TD></TR>
	<TR><TD>&nbsp;</TD></TR>
	<TR><TD COLSPAN=2 class="form_heading">Please select classes to enter</TD></TR>
	<% if @event.isAgility then %>
	<TR><TD class="form_label_cell">Select Agility Class</TD><TD><%= select_tag(:agility, options_for_select([['-', ''], ['Novice', 'AD'], ['Excellent', 'ADX'], ['Masters', 'ADM']])) %></TD></TR>
	<% end	%>
	<% if @event.isAgility then %>
	<TR><TD class="form_label_cell">Select Jumping Class</TD><TD><%= select_tag(:jumping, options_for_select([['-', ''], ['Novice', 'JD'], ['Excellent', 'JDX'], ['Masters', 'JDM']])) %></TD></TR>
	<% end	%>
	<% if @event.isJDO then %>
	<TR><TD class="form_label_cell">Open Jumping</TD><TD><%= check_box(:open, "JDO") %></TD></TR>
	<% end %>
	<% if @event.isADO then %>
	<TR><TD class="form_label_cell">Open Agility</TD><TD><%= check_box(:open, "ADO") %></TD></TR>
	<% end %>
	<% if @event.isSnooker then %>
	<TR><TD class="form_label_cell">Select Snooker</TD><TD><%= select_tag(:snooker, options_for_select([['-', ''], ['Novice', 'SD'], ['Excellent', 'SDX'], ['Masters', 'SDM']])) %></TD></TR>
	<% end	%>
	<% if @event.isGamblers then %>
	<TR><TD class="form_label_cell">Select Gamblers</TD><TD><%= select_tag(:gamblers, options_for_select([['-', ''], ['Novice', 'GD'], ['Excellent', 'GDX'], ['Masters', 'GDM']])) %></TD></TR>
	<% end	%>
	<TR><TD>&nbsp;</TD></TR>
	<TR><TD COLSPAN=2 style="text-align: center;"><%= submit_tag 'Save' %></TD></TR>
	</TABLE>
<% end %>



<%= form_tag do_entry_path do %>

	<HR>
	
	<p class="required">* Required field</p>
	<div class="fieldSet">
		<fieldset>
			<legend>Handler Details</legend>
			<p><label class="field">E-mail:</label><%= text_field_tag(:handler_email) %></p>
			<p><label class="field">First name:</label><%= text_field_tag(:handler_first_name) %></p>
			<p><label class="field">Last name:</label><%= text_field_tag(:handler_last_name) %></p>
			
			<legend>Dog Details</legend>
			<p><label class="field">Name:</label><%= text_field_tag(:dog_name) %></p>
			<p><label class="field">Titles:</label><%= text_field_tag(:dog_titles) %></p>
			<p><label class="field">Registration Number:</label><%= text_field_tag(:dog_registration_number) %></p>
			<p><label class="field">Breed:</label><%= text_field_tag(:dog_breed) %></p>
			<p><label class="field">Height:</label><%= select_tag(:dog_height, options_for_select([['-', ''], ['200', '200'], ['300', '300'], ['400', '400'], ['500', '500'], ['600', '600']])) %></p>
			
			<legend>Please select classes to enter</legend>
			<% if @event.isAgility then %>
			<p><label class="field">Agility</label><%= select_tag(:agility, options_for_select([['-', ''], ['Novice', 'AD'], ['Excellent', 'ADX'], ['Masters', 'ADM']])) %></p>
			<% end	%>
			<% if @event.isAgility then %>
			<p><label class="field">Jumping</label><%= select_tag(:jumping, options_for_select([['-', ''], ['Novice', 'JD'], ['Excellent', 'JDX'], ['Masters', 'JDM']])) %></p>
			<% end	%>
			<% if @event.isJDO then %>
			<p><label class="field">Open Jumping</label><%= check_box(:open, "JDO") %></p>
			<% end %>
			<% if @event.isADO then %>
			<p><label class="field">Open Agility</label><%= check_box(:open, "ADO") %></p>
			<% end %>
			<% if @event.isSnooker then %>
			<p><label class="field">Snooker</label><%= select_tag(:snooker, options_for_select([['-', ''], ['Novice', 'SD'], ['Excellent', 'SDX'], ['Masters', 'SDM']])) %></p>
			<% end	%>
			<% if @event.isGamblers then %>
			<p><label class="field">Gamblers</label><%= select_tag(:gamblers, options_for_select([['-', ''], ['Novice', 'GD'], ['Excellent', 'GDX'], ['Masters', 'GDM']])) %></p>
			<% end	%>
			<p><%= submit_tag 'Save' %></p>

	
		</fieldset>
	</div>
<% end %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Hosting club</th>
      <th>Isagility</th>
      <th>Isjumping</th>
      <th>Isado</th>
      <th>Isjdo</th>
      <th>Issnooker</th>
      <th>Isgamblers</th>
      <th>Isstratpairs</th>
      <th>Trial datetime</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.hosting_club %></td>
        <td><%= event.isAgility %></td>
        <td><%= event.isJumping %></td>
        <td><%= event.isADO %></td>
        <td><%= event.isJDO %></td>
        <td><%= event.isSnooker %></td>
        <td><%= event.isGamblers %></td>
        <td><%= event.isStratPairs %></td>
        <td><%= event.trial_datetime %></td>
        <td><%= event.notes %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hosting club:</strong>
  <%= @event.hosting_club %>
</p>

<p>
  <strong>Isagility:</strong>
  <%= @event.isAgility %>
</p>

<p>
  <strong>Isjumping:</strong>
  <%= @event.isJumping %>
</p>

<p>
  <strong>Isado:</strong>
  <%= @event.isADO %>
</p>

<p>
  <strong>Isjdo:</strong>
  <%= @event.isJDO %>
</p>

<p>
  <strong>Issnooker:</strong>
  <%= @event.isSnooker %>
</p>

<p>
  <strong>Isgamblers:</strong>
  <%= @event.isGamblers %>
</p>

<p>
  <strong>Isstratpairs:</strong>
  <%= @event.isStratPairs %>
</p>

<p>
  <strong>Trial datetime:</strong>
  <%= @event.trial_datetime %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @event.notes %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>